name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build the Targets
      run: |
        cmake .
        make tests -j4
    - name: Run Test
      run: make test
